#include "nit.common.h"
extern const int COLOR_c__CArray___native_array;
extern const char FILE_c[];
extern const int COLOR_c__CArray__NATIVE;
extern const int COLOR_core__kernel__Object__init;
extern const int COLOR_core__array__AbstractArrayRead___length;
extern const int COLOR_c__CArray__destroyed;
extern const struct type type_core__Int;
extern const char FILE_core__kernel[];
extern const int COLOR_core__abstract_collection__Collection__length;
extern const int COLOR_c__CArray__native_array;
extern const int COLOR_c__NativeCArray___91d_93d;
extern const int COLOR_c__CArray___35dE;
extern const int COLOR_c__NativeCArray___91d_93d_61d;
extern const int COLOR_c__CArray___destroyed;
extern const int COLOR_core__kernel__Pointer__free;
extern const int COLOR_c__CArray__destroyed_61d;
val* NEW_c__NativeCIntArray(const struct type* type);
extern const struct type type_c__NativeCIntArray;
extern const int COLOR_c__NativeCIntArray__new;
extern const int COLOR_c__CArray__native_array_61d;
extern const int COLOR_c__CArray__init;
val* NEW_c__CIntArray(const struct type* type);
extern const struct type type_c__CIntArray;
extern const int COLOR_c__CIntArray__init;
val* core__range___Int___times(long self);
extern const int COLOR_core__abstract_collection__Collection__iterator;
extern const int COLOR_core__abstract_collection__Iterator__is_ok;
extern const int COLOR_core__abstract_collection__Iterator__item;
extern const int COLOR_core__abstract_collection__SequenceRead___91d_93d;
extern const int COLOR_c__CArray___91d_93d_61d;
extern const int COLOR_core__abstract_collection__Iterator__next;
extern const int COLOR_core__abstract_collection__Iterator__finish;
val* BOX_core__Pointer(void*);
extern const struct class class_c__NativeCIntArray;
void* c___new_NativeCIntArray___impl( long size );
long c___NativeCIntArray__index___impl( void* self, long index );
long c___c__NativeCIntArray___NativeCArray___91d_93d(val* self, long p0);
void c___NativeCIntArray__index_assign___impl( void* self, long index, long val );
void c___c__NativeCIntArray___NativeCArray___91d_93d_61d(val* self, long p0, long p1);
void* c___NativeCIntArray__plus___impl( void* self, long offset );
val* NEW_c__NativeCUInt16Array(const struct type* type);
extern const struct type type_c__NativeCUInt16Array;
extern const int COLOR_c__NativeCUInt16Array__new;
val* NEW_c__CUInt16Array(const struct type* type);
extern const struct type type_c__CUInt16Array;
extern const int COLOR_c__CUInt16Array__init;
extern const struct class class_c__NativeCUInt16Array;
void* c___new_NativeCUInt16Array___impl( long size );
long c___NativeCUInt16Array__index___impl( void* self, long index );
long c___c__NativeCUInt16Array___NativeCArray___91d_93d(val* self, long p0);
void c___NativeCUInt16Array__index_assign___impl( void* self, long index, long val );
void c___c__NativeCUInt16Array___NativeCArray___91d_93d_61d(val* self, long p0, long p1);
void* c___NativeCUInt16Array__plus___impl( void* self, long offset );
val* NEW_c__NativeCByteArray(const struct type* type);
extern const struct type type_c__NativeCByteArray;
extern const int COLOR_c__NativeCByteArray__new;
val* NEW_c__CByteArray(const struct type* type);
extern const struct type type_c__CByteArray;
extern const int COLOR_c__CByteArray__init;
extern const int COLOR_c__NativeCByteArray__move;
extern const struct class class_c__NativeCByteArray;
void* c___new_NativeCByteArray___impl( long size );
unsigned char c___NativeCByteArray__index___impl( void* self, long index );
unsigned char c___c__NativeCByteArray___NativeCArray___91d_93d(val* self, long p0);
val* BOX_core__Byte(unsigned char);
extern const struct type type_core__Byte;
void c___NativeCByteArray__index_assign___impl( void* self, long index, unsigned char val );
void c___c__NativeCByteArray___NativeCArray___91d_93d_61d(val* self, long p0, unsigned char p1);
void* c___NativeCByteArray__plus___impl( void* self, long offset );
void c___NativeCByteArray_move___impl( void* self, long dst_offset, long src_offset, long n );
val* NEW_c__NativeCStringArray(const struct type* type);
extern const struct type type_c__NativeCStringArray;
extern const int COLOR_c__NativeCStringArray__new;
val* NEW_c__CNativeStringArray(const struct type* type);
extern const struct type type_c__CNativeStringArray;
extern const int COLOR_c__CNativeStringArray__init;
extern const struct class class_c__NativeCStringArray;
void* c___new_NativeCStringArray___impl( long size );
char* c___NativeCStringArray__index___impl( void* self, long index );
char* c___c__NativeCStringArray___NativeCArray___91d_93d(val* self, long p0);
val* BOX_core__NativeString(void*);
extern const int COLOR_c__NativeCArray__E;
extern const struct type type_core__NativeString;
void c___NativeCStringArray__index_assign___impl( void* self, long index, char* val );
void c___c__NativeCStringArray___NativeCArray___91d_93d_61d(val* self, long p0, char* p1);
void* c___NativeCStringArray__plus___impl( void* self, long offset );
char* c___NativeString__plus___impl( char* self, long offset );
char* c___core__NativeString___NativeCArray___43d(char* self, long p0);
