#include "nit.common.h"
extern const int COLOR_core__file__FileStream___path;
extern const int COLOR_core__file__FileStream___file;
extern const char FILE_core__file[];
extern const int COLOR_core__file__NativeFile__file_stat;
extern const int COLOR_core__kernel__Pointer__address_is_null;
val* NEW_core__FileStat(const struct type* type);
extern const struct type type_core__FileStat;
extern const int COLOR_core__file__FileStat__stat_61d;
extern const int COLOR_core__kernel__Object__init;
extern const int COLOR_core__file__NativeFile__fileno;
extern const int COLOR_core__kernel__Object___61d_61d;
extern const int COLOR_core__stream__Stream__last_error;
extern const int COLOR_core__kernel__Object___33d_61d;
val* NEW_core__IOError(const struct type* type);
extern const struct type type_core__IOError;
val* core__flat___NativeString___to_s_full(char* self, long p0, long p1);
extern const int COLOR_core__error__Error__message_61d;
extern const int COLOR_core__stream__Stream__last_error_61d;
extern const int COLOR_core__file__NativeFile__io_close;
val* NEW_core__NativeArray(int length, const struct type* type);
extern const struct type type_core__NativeArray__core__String;
extern const int COLOR_core__kernel__Sys__errno;
val* core__abstract_text___Int___strerror(long self);
extern const int COLOR_core__abstract_text__NativeArray__native_to_s;
extern const struct type type_core__Int;
extern const char FILE_core__kernel[];
extern const int COLOR_core__file__NativeFile__set_buffering_type;
extern const int COLOR_core__stream__Reader__eof;
extern const int COLOR_core__stream__Stream__close;
val* NEW_core__file__NativeFile(const struct type* type);
extern const struct type type_core__file__NativeFile;
extern const int COLOR_core__file__FileStream__path;
extern const int COLOR_core__abstract_text__Text__to_cstring;
extern const int COLOR_core__file__NativeFile__io_open_read;
extern const int COLOR_core__file__FileReader__end_reached_61d;
extern const int COLOR_core__stream__BufferedReader__buffer_reset;
extern const int COLOR_core___core__FileReader___core__stream__Stream__close;
extern const int COLOR_core__stream__BufferedReader___buffer;
extern const int COLOR_core__stream__BufferedReader___buffer_capacity;
extern const int COLOR_core__file__NativeFile__io_read;
extern const int COLOR_core__file__NativeFile__ferror;
extern const int COLOR_core__stream__BufferedReader___buffer_length;
extern const int COLOR_core__stream__BufferedReader___buffer_pos;
extern const int COLOR_core__file__FileReader___end_reached;
extern const int COLOR_core__file__FileStream__path_61d;
extern const int COLOR_core__stream__BufferedReader__prepare_buffer;
extern const int COLOR_core__file__Sys__read_only;
val* core__file___Int___fd_to_stream(long self, char* p0);
val* core__flat___Int___core__abstract_text__Object__to_s(long self);
extern const int COLOR_core__file__FileStream__fd;
extern const int COLOR_core__file__FileReader__native_poll_in;
long core__file___FileReader_native_poll_in___impl( struct nitni_instance * self, long fd );
extern const int COLOR_core__file__FileWriter___is_writable;
extern const int COLOR_core__bytes__Bytes__items;
extern const int COLOR_core__abstract_collection__Collection__length;
extern const int COLOR_core__file__FileWriter__write_native;
extern const int COLOR_core__file__Text__write_native_to;
extern const int COLOR_core__file__NativeFile__write_byte;
extern const int COLOR_core___core__FileWriter___core__stream__Stream__close;
extern const int COLOR_core__file__NativeFile__io_write;
extern const int COLOR_core__file__NativeFile__io_open_write;
extern const int COLOR_core__file__FileWriter__is_writable_61d;
extern const int COLOR_core__file__Sys__wipe_write;
val* BOX_core__Pointer(void*);
extern const struct class class_core__file__NativeFile;
void* core__file___Int_fd_to_stream___impl( long self, char* mode );
extern const int COLOR_core___core__Stdin___core__kernel__Object__init;
extern const int COLOR_core__file__NativeFile__native_stdin;
extern const int COLOR_core___core__Stdout___core__kernel__Object__init;
extern const int COLOR_core__file__NativeFile__native_stdout;
extern const int COLOR_core__file__Sys__buffer_mode_line;
extern const int COLOR_core__file__FileStream__set_buffering_mode;
extern const int COLOR_core___core__Stderr___core__kernel__Object__init;
extern const int COLOR_core__file__NativeFile__native_stderr;
val* NEW_core__FileWriter(const struct type* type);
extern const struct type type_core__FileWriter;
extern const int COLOR_core__file__FileWriter__open;
extern const int COLOR_core__stream__Writable__write_to;
extern const int COLOR_core__file__Path___path;
extern const int COLOR_core__file__Path__path;
extern const int COLOR_core__file__Path___filename;
extern const int COLOR_core__file__String__basename;
extern const int COLOR_core__file__Path___simplified;
extern const int COLOR_core__file__String__simplify_path;
extern const int COLOR_core__file__Text__to_path;
extern const int COLOR_core__file__Path__simplified_61d;
extern const int COLOR_core__file__Path___dir;
extern const int COLOR_core__file__String__dirname;
extern const int COLOR_core__file__Path___last_error;
extern const int COLOR_core__file__Path__stat;
val* core__file___NativeString___file_stat(char* self);
extern const int COLOR_core__file__Path__last_error_61d;
val* core__file___NativeString___file_lstat(char* self);
short int core__file___NativeString___file_delete(char* self);
extern const int COLOR_core__file__Path__open_ro;
extern const int COLOR_core__file__Path__open_wo;
extern const int COLOR_core__stream__Reader__read;
extern const int COLOR_core__stream__Writer__write;
val* NEW_core__FileReader(const struct type* type);
extern const struct type type_core__FileReader;
extern const int COLOR_core__file__FileReader__open;
extern const int COLOR_core__file__Path__read_all_bytes;
extern const int COLOR_core__abstract_text__Object__to_s;
extern const int COLOR_core__stream__Reader__read_all_bytes;
extern const int COLOR_core__stream__Reader__read_lines;
extern const int COLOR_core__stream__Reader__each_line;
extern const int COLOR_core__stream__LineIterator__close_on_finish_61d;
val* NEW_core__Array(const struct type* type);
extern const struct type type_core__Array__core__Path;
val* NEW_core__file__NativeDir(const struct type* type);
extern const struct type type_core__file__NativeDir;
extern const int COLOR_core__file__NativeDir__opendir;
extern const int COLOR_core__file__NativeDir__readdir;
short int core___core__Pointer___address_is_null(val* self);
val* core__flat___NativeString___to_s_with_copy(char* self);
val* NEW_core__Path(const struct type* type);
extern const struct type type_core__Path;
extern const int COLOR_core__file__String___47d;
extern const int COLOR_core__file__Path__path_61d;
extern const int COLOR_core__abstract_collection__SimpleCollection__add;
extern const int COLOR_core__file__NativeDir__closedir;
extern const int COLOR_core__file__Path__files;
extern const int COLOR_core__abstract_collection__Collection__iterator;
extern const int COLOR_core__abstract_collection__Iterator__is_ok;
extern const int COLOR_core__abstract_collection__Iterator__item;
extern const int COLOR_core__file__Path__link_stat;
extern const int COLOR_core__file__Path__last_error;
extern const int COLOR_core__file__FileStat__is_dir;
extern const int COLOR_core__file__Path__rmdir;
extern const int COLOR_core__file__Path__delete;
extern const int COLOR_core__abstract_collection__Iterator__next;
extern const int COLOR_core__abstract_collection__Iterator__finish;
short int core__file___NativeString___rmdir(char* self);
extern const int COLOR_core__file__Path__simplified;
extern const int COLOR_core__kernel__Object__hash;
extern const int COLOR_core___core__Path___core__kernel__Object__init;
extern const int COLOR_core__file__FileStat___stat;
extern const int COLOR_core__file__FileStat___finalized;
extern const int COLOR_core__file__FileStat__finalized;
extern const int COLOR_core__file__FileStat__stat;
extern const int COLOR_core__kernel__Pointer__free;
extern const int COLOR_core__file__FileStat__finalized_61d;
extern const int COLOR_core__file__NativeFileStat__atime;
extern const int COLOR_core__file__FileStat__last_access_time;
extern const int COLOR_core__file__NativeFileStat__mtime;
extern const int COLOR_core__file__FileStat__last_modification_time;
extern const int COLOR_core__file__NativeFileStat__size;
extern const int COLOR_core__file__NativeFileStat__is_reg;
extern const int COLOR_core__file__FileStat__is_file;
extern const int COLOR_core__file__NativeFileStat__is_dir;
extern const int COLOR_core__file__NativeFileStat__is_lnk;
extern const int COLOR_core__file__NativeFileStat__ctime;
extern const int COLOR_core__file__FileStat__last_status_change_time;
extern const int COLOR_core__file__NativeFileStat__mode;
extern const int COLOR_core__file__NativeFileStat__is_chr;
extern const int COLOR_core__file__NativeFileStat__is_blk;
extern const int COLOR_core__file__NativeFileStat__is_fifo;
extern const int COLOR_core__file__NativeFileStat__is_sock;
extern const int COLOR_core___core__FileStat___core__kernel__Object__init;
extern const int COLOR_core__abstract_text__Text__substrings;
extern const int COLOR_core__abstract_collection__Iterator__iterator;
extern const int COLOR_core__abstract_text__Text__bytelen;
short int core__file___NativeString___file_exists(char* self);
extern const int COLOR_core__file__Path__copy;
extern const int COLOR_core__file__String__file_extension;
extern const int COLOR_core__abstract_text__Text__has_suffix;
extern const int COLOR_core__abstract_text__Text__length;
extern const int COLOR_core__abstract_text__Text__substring;
extern const int COLOR_core__abstract_text__Text__chars;
extern const int COLOR_core__abstract_collection__SequenceRead___91d_93d;
extern const int COLOR_core__abstract_collection__SequenceRead__last_index_of_from;
extern const int COLOR_core__file__String__strip_extension;
char* core__file___NativeString___file_realpath(char* self);
extern const int COLOR_core__file__String__file_exists;
void core___core__Pointer___free(val* self);
extern const int COLOR_core__string_search__Text__split_with;
extern const struct type type_core__Array__core__String;
extern const int COLOR_core__abstract_collection__Collection__is_empty;
extern const int COLOR_core__abstract_collection__SequenceRead__last;
extern const int COLOR_core__abstract_collection__Sequence__pop;
extern const int COLOR_core__abstract_collection__Sequence__push;
extern const int COLOR_core__abstract_collection__Collection__first;
extern const int COLOR_core__abstract_text__Collection__join;
extern const int COLOR_core__abstract_text__Text__is_empty;
extern const int COLOR_core__abstract_text__Text__last;
extern const int COLOR_core__abstract_text__Text__has_prefix;
extern const int COLOR_core__file__String__join_path;
extern const int COLOR_core__file__Sys__getcwd;
extern const int COLOR_core__string_search__Text__split;
extern const int COLOR_core__abstract_collection__Sequence__shift;
extern const int COLOR_core__abstract_text__String___42d;
extern const int COLOR_core__abstract_text__String___43d;
val* NEW_core__FlatBuffer(const struct type* type);
extern const struct type type_core__FlatBuffer;
extern const int COLOR_core__abstract_text__Buffer__add;
extern const int COLOR_core__abstract_text__Buffer__append;
short int core__file___NativeString___file_mkdir(char* self);
short int core__file___NativeString___file_chdir(char* self);
extern const int COLOR_core__abstract_collection__SequenceRead__last_index_of;
extern const int COLOR_core__abstract_text__FlatText__items;
extern const int COLOR_core__flat__FlatText__first_byte;
extern const int COLOR_core__abstract_text__FlatText___items;
extern const int COLOR_core__flat__FlatText__last_byte;
extern const int COLOR_core__flat__FlatString___first_byte;
unsigned char core___core__Char___ascii(uint32_t self);
val* NEW_core__FlatString(const struct type* type);
extern const struct type type_core__FlatString;
extern const int COLOR_core__flat__FlatString__with_infos;
int core__file___NativeString_file_exists___impl( char* self );
extern const struct type type_core__file__NativeFileStat;
extern const struct class class_core__file__NativeFileStat;
void* core__file___NativeString_file_stat___impl( char* self );
void* core__file___NativeString_file_lstat___impl( char* self );
int core__file___NativeString_file_mkdir___impl( char* self );
int core__file___NativeString_rmdir___impl( char* self );
int core__file___NativeString_file_delete___impl( char* self );
int core__file___NativeString_file_chdir___impl( char* self );
char* core__file___NativeString_file_realpath___impl( char* self );
long core__file___NativeFileStat_mode___impl( void* self );
long core__file___NativeFileStat_atime___impl( void* self );
long core__file___NativeFileStat_ctime___impl( void* self );
long core__file___NativeFileStat_mtime___impl( void* self );
long core__file___NativeFileStat_size___impl( void* self );
int core__file___NativeFileStat_is_reg___impl( void* self );
int core__file___NativeFileStat_is_dir___impl( void* self );
int core__file___NativeFileStat_is_chr___impl( void* self );
int core__file___NativeFileStat_is_blk___impl( void* self );
int core__file___NativeFileStat_is_fifo___impl( void* self );
int core__file___NativeFileStat_is_lnk___impl( void* self );
int core__file___NativeFileStat_is_sock___impl( void* self );
long core__file___NativeFile_io_read___impl( void* self, char* buf, long len );
long core__file___NativeFile_io_write___impl( void* self, char* buf, long from, long len );
long core__file___NativeFile_write_byte___impl( void* self, unsigned char value );
long core__file___NativeFile_io_close___impl( void* self );
void* core__file___NativeFile_file_stat___impl( void* self );
int core__file___NativeFile_ferror___impl( void* self );
long core__file___NativeFile_fileno___impl( void* self );
long core__file___NativeFile_flush___impl( void* self );
long core__file___NativeFile_set_buffering_type___impl( void* self, long buf_length, long mode );
void* core__file___new_NativeFile_io_open_read___impl( char* path );
void* core__file___new_NativeFile_io_open_write___impl( char* path );
void* core__file___new_NativeFile_native_stdin___impl(  );
void* core__file___new_NativeFile_native_stdout___impl(  );
void* core__file___new_NativeFile_native_stderr___impl(  );
extern const struct class class_core__file__NativeDir;
void* core__file___new_NativeDir_opendir___impl( char* path );
void core__file___NativeDir_closedir___impl( void* self );
char* core__file___NativeDir_readdir___impl( void* self );
extern const int COLOR_core__file__Sys___stdin;
val* NEW_core__Stdin(const struct type* type);
extern const struct type type_core__Stdin;
extern const int COLOR_core__file__Sys___stdout;
val* NEW_core__Stdout(const struct type* type);
extern const struct type type_core__Stdout;
extern const int COLOR_core__file__Sys___stderr;
val* NEW_core__Stderr(const struct type* type);
extern const struct type type_core__Stderr;
long core__file___Sys_buffer_mode_full___impl( struct nitni_instance * self );
long core__file___Sys_buffer_mode_line___impl( struct nitni_instance * self );
long core__file___Sys_buffer_mode_none___impl( struct nitni_instance * self );
extern const struct type type_core__Array__core__Int;
val* NEW_core__HashMap(const struct type* type);
extern const struct type type_core__HashMap__core__Int__core__FileStream;
extern const int COLOR_core__abstract_collection__Map___91d_93d_61d;
extern const int COLOR_core__file__Sys__intern_poll;
extern const int COLOR_core__abstract_collection__MapRead___91d_93d;
struct nitni_instance * core__file___Sys_intern_poll___impl( struct nitni_instance * self, struct nitni_instance * in_fds, struct nitni_instance * out_fds );
extern const int COLOR_core__file__Sys__stdout;
extern const int COLOR_core__abstract_text__Collection__plain_to_s;
extern const int COLOR_core__file__Sys__stderr;
extern const int COLOR_core__file__Sys__stdin;
extern const int COLOR_core__stream__Reader__read_char;
extern const int COLOR_core__stream__Reader__read_line;
extern const int COLOR_core__file__Sys__native_getcwd;
val* core__flat___NativeString___core__abstract_text__Object__to_s(char* self);
char* core__file___Sys_native_getcwd___impl( struct nitni_instance * self );
