#include "nit.common.h"
extern const int COLOR_core__kernel__Object___61d_61d;
void core___core__Char___Object__output(uint32_t self);
extern const int COLOR_core__kernel__Object__object_id;
extern const int COLOR_core__kernel__Sys__main;
long core__kernel___Sys_errno___impl( struct nitni_instance * self );
extern const char FILE_core__kernel[];
extern const int COLOR_core__kernel__Comparable__OTHER;
extern const int COLOR_core__kernel__Comparable___60d;
extern const int COLOR_core__kernel__Comparable___60d_61d;
extern const int COLOR_core__kernel__Comparable___62d;
extern const int COLOR_core__kernel__Discrete__successor;
extern const struct type type_core__Int;
extern const int COLOR_core__kernel__Numeric__zero;
long core___core__Bool___to_i(short int self);
long core___core__Bool___Object__hash(short int self);
extern const struct class class_core__Float;
extern const struct type type_core__Float;
val* BOX_core__Float(double);
double core___core__Float___Numeric__to_f(double self);
double core___core__Float___Numeric__zero(double self);
extern const int COLOR_core__kernel__Numeric__to_f;
double core___core__Float___Numeric__value_of(double self, val* p0);
long core___core__Float___Comparable___60d_61d_62d(double self, double p0);
short int core___core__Float___Comparable__is_between(double self, double p0, double p1);
double core___core__Float___Comparable__max(double self, double p0);
double core___core__Float___Comparable__min(double self, double p0);
extern const struct type type_core__Byte;
unsigned char core___core__Byte___Discrete__successor(unsigned char self, long p0);
val* BOX_core__Byte(unsigned char);
unsigned char core___core__Byte___Discrete__predecessor(unsigned char self, long p0);
long core___core__Byte___Object__hash(unsigned char self);
extern const struct class class_core__Byte;
unsigned char core___core__Byte___Numeric__zero(unsigned char self);
extern const int COLOR_core__kernel__Numeric__to_b;
unsigned char core___core__Byte___Numeric__value_of(unsigned char self, val* p0);
unsigned char core___core__Byte___Numeric__to_b(unsigned char self);
long core___core__Byte___Discrete__distance(unsigned char self, unsigned char p0);
long core___core__Byte___Comparable___60d_61d_62d(unsigned char self, unsigned char p0);
short int core___core__Byte___Comparable__is_between(unsigned char self, unsigned char p0, unsigned char p1);
unsigned char core___core__Byte___Comparable__max(unsigned char self, unsigned char p0);
unsigned char core___core__Byte___Comparable__min(unsigned char self, unsigned char p0);
long core___core__Int___Discrete__successor(long self, long p0);
long core___core__Int___Discrete__predecessor(long self, long p0);
long core___core__Int___Object__hash(long self);
long core___core__Int___Numeric__zero(long self);
extern const int COLOR_core__kernel__Numeric__to_i;
long core___core__Int___Numeric__value_of(long self, val* p0);
long core___core__Int___Numeric__to_i(long self);
long core___core__Int___Discrete__distance(long self, long p0);
long core___core__Int___Comparable___60d_61d_62d(long self, long p0);
short int core___core__Int___Comparable__is_between(long self, long p0, long p1);
long core___core__Int___Comparable__max(long self, long p0);
long core___core__Int___Comparable__min(long self, long p0);
long core___core__Int___digit_count_base_95d10(long self);
void core__kernel___Char_output___impl( uint32_t self );
long core___core__Char___Object__hash(uint32_t self);
extern const struct type type_core__Char;
long core___core__Char___Discrete__distance(uint32_t self, uint32_t p0);
short int core___core__Char___is_digit(uint32_t self);
uint32_t core___core__Char___to_lower(uint32_t self);
short int core___core__Char___is_upper(uint32_t self);
short int core___core__Char___is_lower(uint32_t self);
int core__kernel___Pointer_address_is_null___impl( void* self );
void core__kernel___Pointer_free___impl( void* self );
