#include "nit.common.h"
extern const int COLOR_core__kernel__Numeric__to_i;
extern const struct type type_core__Int8;
extern const char FILE_core__fixed_ints[];
int8_t core___core__Int8___core__kernel__Discrete__successor(int8_t self, long p0);
val* BOX_core__Int8(int8_t);
int8_t core___core__Int8___core__kernel__Discrete__predecessor(int8_t self, long p0);
long core___core__Int8___core__kernel__Object__hash(int8_t self);
extern const struct class class_core__Int8;
extern const int COLOR_core__kernel__Comparable__OTHER;
int8_t core___core__Int8___core__kernel__Numeric__zero(int8_t self);
extern const int COLOR_core__fixed_ints__Numeric__to_i8;
int8_t core___core__Int8___core__kernel__Numeric__value_of(int8_t self, val* p0);
int8_t core___core__Int8___Numeric__to_i8(int8_t self);
uint32_t core__fixed_ints___Int8_ascii___impl( int8_t self );
long core___core__Int8___core__kernel__Discrete__distance(int8_t self, int8_t p0);
long core___core__Int8___core__kernel__Comparable___60d_61d_62d(int8_t self, int8_t p0);
short int core___core__Int8___core__kernel__Comparable__is_between(int8_t self, int8_t p0, int8_t p1);
int8_t core___core__Int8___core__kernel__Comparable__max(int8_t self, int8_t p0);
int8_t core___core__Int8___core__kernel__Comparable__min(int8_t self, int8_t p0);
long core__fixed_ints___Int8_to_s_len___impl( int8_t self );
void core__fixed_ints___Int8_native_to_s___impl( int8_t self, char* nstr, long strlen );
long core___core__Int8___to_s_len(int8_t self);
extern const struct type type_core__Int;
extern const char FILE_core__kernel[];
void core___core__Int8___native_to_s(int8_t self, char* p0, long p1);
val* core__flat___NativeString___to_s_with_length(char* self, long p0);
val* core___core__Int8___core__abstract_text__Object__to_s(int8_t self);
extern const struct type type_core__Int16;
int16_t core___core__Int16___core__kernel__Discrete__successor(int16_t self, long p0);
val* BOX_core__Int16(int16_t);
int16_t core___core__Int16___core__kernel__Discrete__predecessor(int16_t self, long p0);
long core___core__Int16___core__kernel__Object__hash(int16_t self);
extern const struct class class_core__Int16;
uint32_t core__fixed_ints___Int16_ascii___impl( int16_t self );
int16_t core___core__Int16___core__kernel__Numeric__zero(int16_t self);
extern const int COLOR_core__fixed_ints__Numeric__to_i16;
int16_t core___core__Int16___core__kernel__Numeric__value_of(int16_t self, val* p0);
int16_t core___core__Int16___Numeric__to_i16(int16_t self);
long core___core__Int16___core__kernel__Discrete__distance(int16_t self, int16_t p0);
long core___core__Int16___core__kernel__Comparable___60d_61d_62d(int16_t self, int16_t p0);
short int core___core__Int16___core__kernel__Comparable__is_between(int16_t self, int16_t p0, int16_t p1);
int16_t core___core__Int16___core__kernel__Comparable__max(int16_t self, int16_t p0);
int16_t core___core__Int16___core__kernel__Comparable__min(int16_t self, int16_t p0);
long core__fixed_ints___Int16_to_s_len___impl( int16_t self );
void core__fixed_ints___Int16_native_to_s___impl( int16_t self, char* nstr, long strlen );
long core___core__Int16___to_s_len(int16_t self);
void core___core__Int16___native_to_s(int16_t self, char* p0, long p1);
val* core___core__Int16___core__abstract_text__Object__to_s(int16_t self);
extern const struct type type_core__UInt16;
uint16_t core___core__UInt16___core__kernel__Discrete__successor(uint16_t self, long p0);
val* BOX_core__UInt16(uint16_t);
uint16_t core___core__UInt16___core__kernel__Discrete__predecessor(uint16_t self, long p0);
long core___core__UInt16___core__kernel__Object__hash(uint16_t self);
extern const struct class class_core__UInt16;
uint16_t core___core__UInt16___core__kernel__Numeric__zero(uint16_t self);
extern const int COLOR_core__fixed_ints__Numeric__to_u16;
uint16_t core___core__UInt16___core__kernel__Numeric__value_of(uint16_t self, val* p0);
uint32_t core__fixed_ints___UInt16_ascii___impl( uint16_t self );
uint16_t core___core__UInt16___Numeric__to_u16(uint16_t self);
long core___core__UInt16___core__kernel__Discrete__distance(uint16_t self, uint16_t p0);
long core___core__UInt16___core__kernel__Comparable___60d_61d_62d(uint16_t self, uint16_t p0);
short int core___core__UInt16___core__kernel__Comparable__is_between(uint16_t self, uint16_t p0, uint16_t p1);
uint16_t core___core__UInt16___core__kernel__Comparable__max(uint16_t self, uint16_t p0);
uint16_t core___core__UInt16___core__kernel__Comparable__min(uint16_t self, uint16_t p0);
long core__fixed_ints___UInt16_to_s_len___impl( uint16_t self );
void core__fixed_ints___UInt16_native_to_s___impl( uint16_t self, char* nstr, long strlen );
long core___core__UInt16___to_s_len(uint16_t self);
void core___core__UInt16___native_to_s(uint16_t self, char* p0, long p1);
val* core___core__UInt16___core__abstract_text__Object__to_s(uint16_t self);
extern const struct type type_core__Int32;
int32_t core___core__Int32___core__kernel__Discrete__successor(int32_t self, long p0);
val* BOX_core__Int32(int32_t);
int32_t core___core__Int32___core__kernel__Discrete__predecessor(int32_t self, long p0);
long core___core__Int32___core__kernel__Object__hash(int32_t self);
extern const struct class class_core__Int32;
uint32_t core__fixed_ints___Int32_ascii___impl( int32_t self );
int32_t core___core__Int32___core__kernel__Numeric__zero(int32_t self);
extern const int COLOR_core__fixed_ints__Numeric__to_i32;
int32_t core___core__Int32___core__kernel__Numeric__value_of(int32_t self, val* p0);
int32_t core___core__Int32___Numeric__to_i32(int32_t self);
long core___core__Int32___core__kernel__Discrete__distance(int32_t self, int32_t p0);
long core___core__Int32___core__kernel__Comparable___60d_61d_62d(int32_t self, int32_t p0);
short int core___core__Int32___core__kernel__Comparable__is_between(int32_t self, int32_t p0, int32_t p1);
int32_t core___core__Int32___core__kernel__Comparable__max(int32_t self, int32_t p0);
int32_t core___core__Int32___core__kernel__Comparable__min(int32_t self, int32_t p0);
long core__fixed_ints___Int32_to_s_len___impl( int32_t self );
void core__fixed_ints___Int32_native_to_s___impl( int32_t self, char* nstr, long strlen );
long core___core__Int32___to_s_len(int32_t self);
void core___core__Int32___native_to_s(int32_t self, char* p0, long p1);
val* core___core__Int32___core__abstract_text__Object__to_s(int32_t self);
extern const struct type type_core__UInt32;
uint32_t core___core__UInt32___core__kernel__Discrete__successor(uint32_t self, long p0);
val* BOX_core__UInt32(uint32_t);
uint32_t core___core__UInt32___core__kernel__Discrete__predecessor(uint32_t self, long p0);
long core___core__UInt32___core__kernel__Object__hash(uint32_t self);
extern const struct class class_core__UInt32;
uint32_t core__fixed_ints___UInt32_ascii___impl( uint32_t self );
uint32_t core___core__UInt32___core__kernel__Numeric__zero(uint32_t self);
extern const int COLOR_core__fixed_ints__Numeric__to_u32;
uint32_t core___core__UInt32___core__kernel__Numeric__value_of(uint32_t self, val* p0);
uint32_t core___core__UInt32___Numeric__to_u32(uint32_t self);
long core___core__UInt32___core__kernel__Discrete__distance(uint32_t self, uint32_t p0);
long core___core__UInt32___core__kernel__Comparable___60d_61d_62d(uint32_t self, uint32_t p0);
short int core___core__UInt32___core__kernel__Comparable__is_between(uint32_t self, uint32_t p0, uint32_t p1);
uint32_t core___core__UInt32___core__kernel__Comparable__max(uint32_t self, uint32_t p0);
uint32_t core___core__UInt32___core__kernel__Comparable__min(uint32_t self, uint32_t p0);
long core__fixed_ints___UInt32_to_s_len___impl( uint32_t self );
void core__fixed_ints___UInt32_native_to_s___impl( uint32_t self, char* nstr, long strlen );
long core___core__UInt32___to_s_len(uint32_t self);
void core___core__UInt32___native_to_s(uint32_t self, char* p0, long p1);
val* core___core__UInt32___core__abstract_text__Object__to_s(uint32_t self);
extern const int COLOR_core__fixed_ints__Text__get_numhead;
val* core__flat___NativeString___to_s_full(char* self, long p0, long p1);
extern const int COLOR_core__kernel__Object___33d_61d;
extern const int COLOR_core__abstract_text__Text__substring_from;
extern const int COLOR_core__abstract_text__Text__length;
extern const int COLOR_core__abstract_text__Text___91d_93d;
extern const int COLOR_core__abstract_text__Text__substring;
extern const int COLOR_core__fixed_ints__Text__get_numext;
long core___core__Int___Discrete__successor(long self, long p0);
extern const int COLOR_core__abstract_text__Text__bytelen;
extern const int COLOR_core__string_search__Text__remove_all;
extern const int COLOR_core__fixed_ints__Text__strip_numhead;
extern const int COLOR_core__kernel__Object___61d_61d;
extern const int COLOR_core__abstract_text__Text__is_hex;
extern const int COLOR_core__abstract_text__Text__is_bin;
extern const int COLOR_core__abstract_text__Text__is_oct;
extern const int COLOR_core__abstract_text__Text__is_dec;
extern const int COLOR_core__fixed_ints__Text__is_int;
extern const int COLOR_core__abstract_text__Text__to_hex;
extern const int COLOR_core__abstract_text__Text__to_oct;
extern const int COLOR_core__abstract_text__Text__to_bin;
short int core__abstract_text___Char___is_numeric(uint32_t self);
extern const int COLOR_core__abstract_text__Text__to_dec;
extern const int COLOR_core__fixed_ints__Text__strip_numext;
extern const int COLOR_core__fixed_ints__Text__is_num;
extern const int COLOR_core__abstract_text__Text__to_i;
val* BOX_core__Byte(unsigned char);
