#include "nit.common.h"
extern const int COLOR_core__error__Error___message;
extern const char FILE_core__error[];
extern const int COLOR_core__error__Error___cause;
extern const int COLOR_core__error__Error__message;
extern const int COLOR_core___core__Error___core__kernel__Object__init;
extern const int COLOR_core__error__MaybeError___maybe_value;
extern const int COLOR_nullable__core__MaybeError___35dV;
extern const int COLOR_core__error__MaybeError___maybe_error;
extern const int COLOR_nullable__core__MaybeError___35dE;
extern const int COLOR_core__error__MaybeError__maybe_error;
extern const int COLOR_core__kernel__Object___33d_61d;
extern const int COLOR_core__error__MaybeError__maybe_value;
extern const int COLOR_core__MaybeError___35dV;
extern const int COLOR_core__MaybeError___35dE;
extern const int COLOR_core__abstract_text__Object__to_s;
extern const int COLOR_core__error__MaybeError__value;
extern const int COLOR_core___core__MaybeError___core__kernel__Object__init;
