#include "nit.common.h"
void core__time___Sys_nanosleep___impl( struct nitni_instance * self, long sec, long nanosec );
long core__time___Sys_get_time___impl( struct nitni_instance * self );
void core__time___Float_sleep___impl( double self );
val* BOX_core__Pointer(void*);
extern const struct type type_core__TimeT;
extern const struct class class_core__TimeT;
void* core__time___new_TimeT___impl(  );
void* core__time___new_TimeT_from_i___impl( long i );
void core__time___TimeT_update___impl( void* self );
struct nitni_instance * core__time___TimeT_ctime___impl( void* self );
val* core__flat___NativeString___to_s_with_copy(char* self);
double core__time___TimeT_difftime___impl( void* self, void* start );
extern const int COLOR_core__time__TimeT__ctime;
val* core__flat___NativeString___to_s_full(char* self, long p0, long p1);
extern const int COLOR_core__string_search__Text__replace;
long core__time___TimeT_to_i___impl( void* self );
extern const struct type type_core__Tm;
extern const struct class class_core__Tm;
void* core__time___new_Tm_gmtime___impl(  );
void* core__time___new_Tm_gmtime_from_timet___impl( void* t );
void* core__time___new_Tm_localtime___impl(  );
void* core__time___new_Tm_localtime_from_timet___impl( void* t );
void* core__time___Tm_to_timet___impl( void* self );
long core__time___Tm_sec___impl( void* self );
long core__time___Tm_min___impl( void* self );
long core__time___Tm_hour___impl( void* self );
long core__time___Tm_mday___impl( void* self );
long core__time___Tm_mon___impl( void* self );
long core__time___Tm_year___impl( void* self );
long core__time___Tm_wday___impl( void* self );
long core__time___Tm_yday___impl( void* self );
int core__time___Tm_is_dst___impl( void* self );
struct nitni_instance * core__time___Tm_asctime___impl( void* self );
struct nitni_instance * core__time___Tm_strftime___impl( void* self, struct nitni_instance * format );
extern const int COLOR_core__abstract_text__Text__to_cstring;
val* core__flat___NativeString___core__abstract_text__Object__to_s(char* self);
extern const int COLOR_core__time__Tm__asctime;
extern const int COLOR_core__time__ISODate___year;
extern const int COLOR_core__time__ISODate___month;
extern const int COLOR_core__time__ISODate___day;
extern const int COLOR_core__time__ISODate___hours;
extern const int COLOR_core__time__ISODate___minutes;
extern const int COLOR_core__time__ISODate___seconds;
extern const int COLOR_core__time__ISODate___timezone;
extern const char FILE_core__time[];
extern const int COLOR_core___core__ISODate___core__kernel__Object__init;
val* NEW_core__Tm(const struct type* type);
extern const int COLOR_core__time__Tm__localtime;
extern const int COLOR_core__time__Tm__year;
extern const struct type type_core__Int;
extern const char FILE_core__kernel[];
extern const int COLOR_core__time__ISODate__year_61d;
extern const int COLOR_core__time__Tm__mon;
extern const int COLOR_core__time__ISODate__month_61d;
extern const int COLOR_core__time__Tm__mday;
extern const int COLOR_core__time__ISODate__day_61d;
extern const int COLOR_core__time__Tm__hour;
extern const int COLOR_core__time__ISODate__hours_61d;
extern const int COLOR_core__time__Tm__min;
extern const int COLOR_core__time__ISODate__minutes_61d;
extern const int COLOR_core__time__Tm__sec;
extern const int COLOR_core__time__ISODate__seconds_61d;
extern const int COLOR_core__kernel__Object__init;
extern const int COLOR_core__abstract_text__Text__substring;
extern const int COLOR_core__abstract_text__Text__to_i;
extern const int COLOR_core__abstract_text__Text__length;
extern const int COLOR_core__time__ISODate__timezone_61d;
val* NEW_core__FlatBuffer(const struct type* type);
extern const struct type type_core__FlatBuffer;
extern const int COLOR_core__time__ISODate__year;
val* core__flat___Int___core__abstract_text__Object__to_s(long self);
extern const int COLOR_core__abstract_text__Buffer__append;
extern const int COLOR_core__abstract_text__Buffer__add;
extern const int COLOR_core__time__ISODate__month;
extern const int COLOR_core__time__ISODate__day;
extern const int COLOR_core__time__ISODate__hours;
extern const int COLOR_core__time__ISODate__minutes;
extern const int COLOR_core__time__ISODate__seconds;
extern const int COLOR_core__time__ISODate__timezone;
extern const int COLOR_core__stream__Writable__write_to_string;
extern const int COLOR_core__kernel__Comparable__OTHER;
extern const int COLOR_core__abstract_text__Object__to_s;
extern const int COLOR_core__kernel__Comparable___60d;
