#include "nit.common.h"
extern const int COLOR_linux__App___assets_dir;
extern const char FILE_linux[];
extern const int COLOR_core__abstract_text__Sys__program_name;
extern const int COLOR_core__file__String__dirname;
val* core__flat___NativeString___to_s_full(char* self, long p0, long p1);
extern const int COLOR_core__file__String___47d;
extern const int COLOR_linux___app__App___setup;
extern const int COLOR_app__app_base__AppComponent__on_create;
extern const int COLOR_app__app_base__AppComponent__on_restore_state;
extern const int COLOR_app__app_base__AppComponent__on_start;
extern const int COLOR_app__app_base__AppComponent__on_resume;
extern const int COLOR_linux___app__App___run;
extern const int COLOR_app__app_base__AppComponent__on_pause;
extern const int COLOR_app__app_base__AppComponent__on_save_state;
extern const int COLOR_app__app_base__AppComponent__on_stop;
extern const int COLOR_app__app_base__AppComponent__on_destroy;
extern const int COLOR_app__app_base__Sys__app;
extern const int COLOR_linux__App__assets_dir;
extern const int COLOR_app__assets__Asset__path;
extern const int COLOR_core__file__Text__to_path;
extern const int COLOR_core__file__Path__open_ro;
extern const int COLOR_core__stream__Reader__read_all;
extern const int COLOR_core__stream__Stream__close;
extern const int COLOR_core__stream__Stream__last_error;
extern const int COLOR_core__kernel__Object___33d_61d;
extern const int COLOR_app__assets__TextAsset__error_61d;
extern const int COLOR_app__assets__TextAsset__to_s_61d;
