#include "nit.common.h"
extern const struct type type_core__Float;
extern const char FILE_core__kernel[];
extern const char FILE_matrix__projection[];
val* NEW_matrix__Matrix(const struct type* type);
extern const struct type type_matrix__Matrix;
extern const int COLOR_matrix__Matrix__identity;
extern const int COLOR_matrix__Matrix___91d_93d_61d;
double core__math___Float___tan(double self);
extern const int COLOR_matrix__projection__Matrix__frustum;
extern const int COLOR_matrix__Matrix__width_61d;
extern const int COLOR_matrix__Matrix__height_61d;
extern const int COLOR_core__kernel__Object__init;
extern const struct type type_core__Int;
extern const int COLOR_matrix__Matrix___91d_93d;
long core___core__Int___Discrete__successor(long self, long p0);
double core__math___Float___sqrt(double self);
double core__math___Float___sin(double self);
double core__math___Float___cos(double self);
extern const int COLOR_matrix__projection__Matrix__rotation;
extern const int COLOR_matrix__Matrix___42d;
extern const int COLOR_matrix__Matrix__items;
extern const int COLOR_matrix__Matrix__items_61d;
