#include "nit.common.h"
extern const int COLOR_physique__engine__App___world;
extern const char FILE_physique__engine[];
extern const int COLOR_physique__engine__App___entities;
extern const int COLOR_physique__engine___app__App___app__app_base__AppComponent__on_create;
extern const int COLOR_physique__engine__App__world;
val* NEW_physique__Gravity(const struct type* type);
extern const struct type type_physique__Gravity;
extern const int COLOR_physique__nitPhysics__Force__intensity_61d;
extern const int COLOR_core__kernel__Object__init;
extern const int COLOR_physique__world__World__add_force;
extern const int COLOR_physique__engine__App__draw_walls;
extern const int COLOR_physique__engine__App__draw_squars;
extern const int COLOR_physique__engine__App__create_player;
extern const int COLOR_physique__engine__App__load_world_entities;
extern const int COLOR_physique__world__World__update;
val* NEW_physique__Polygone(const struct type* type);
extern const struct type type_physique__Polygone;
val* NEW_geometry__Point3d(const struct type* type);
extern const struct type type_geometry__Point3d__core__Float;
val* BOX_core__Float(double);
extern const int COLOR_geometry__points_and_lines__Point__x_61d;
extern const int COLOR_geometry__points_and_lines__Point__y_61d;
extern const int COLOR_geometry__points_and_lines__Point3d__z_61d;
val* NEW_gamnit__Texture(const struct type* type);
extern const struct type type_gamnit__Texture;
val* core__flat___NativeString___to_s_full(char* self, long p0, long p1);
extern const int COLOR_gamnit__textures__Texture__new;
extern const int COLOR_physique__nitSimulation__Entity__position_61d;
extern const int COLOR_physique__nitSimulation__Entity__texture_61d;
val* NEW_physique__Dimensions_95d2d(const struct type* type);
extern const struct type type_physique__Dimensions_95d2d;
extern const int COLOR_physique__nitConstraints__Dimensions_95d2d__height_61d;
extern const int COLOR_physique__nitConstraints__Dimensions_95d2d__width_61d;
extern const int COLOR_physique__nitSimulation__Entity__set_dimensions;
extern const int COLOR_physique__engine__App__entities;
extern const int COLOR_core__abstract_collection__SimpleCollection__add;
val* NEW_physique__Circle(const struct type* type);
extern const struct type type_physique__Circle;
val* NEW_physique__Spritesheet(const struct type* type);
extern const struct type type_physique__Spritesheet;
extern const int COLOR_physique__spritesheet__Spritesheet__ufo_green;
val* NEW_physique__Vector_95d2d(const struct type* type);
extern const struct type type_physique__Vector_95d2d;
double core__math___Float___rand(double self);
extern const int COLOR_physique__nitConstraints__Vector_95d2d__v_x_61d;
extern const int COLOR_physique__nitConstraints__Vector_95d2d__v_y_61d;
extern const int COLOR_physique__nitSimulation__Entity__set_vector;
extern const int COLOR_physique__nitSimulation__Circle__set_elasticity;
val* NEW_physique__Player(const struct type* type);
extern const struct type type_physique__Player;
extern const int COLOR_physique__spritesheet__Spritesheet__ufo_yellow;
extern const int COLOR_physique__nitSimulation__Player__name_61d;
extern const int COLOR_physique__nitSimulation__Player__name;
extern const int COLOR_core__file__Sys__print;
extern const int COLOR_core__abstract_collection__Collection__iterator;
extern const int COLOR_core__abstract_collection__Iterator__is_ok;
extern const int COLOR_core__abstract_collection__Iterator__item;
extern const int COLOR_physique__world__World__add_entity;
extern const int COLOR_core__abstract_collection__Iterator__next;
extern const int COLOR_core__abstract_collection__Iterator__finish;
extern const int COLOR_physique__world__World__entities;
extern const int COLOR_gamnit__flat__App__sprites;
val* NEW_gamnit__Sprite(const struct type* type);
extern const struct type type_gamnit__Sprite;
extern const int COLOR_physique__nitSimulation__Entity__texture;
extern const int COLOR_physique__nitSimulation__Entity__position;
extern const int COLOR_gamnit__flat__Sprite__texture_61d;
extern const int COLOR_gamnit__flat__Sprite__center_61d;
extern const struct type type_mnit__QuitEvent;
extern const struct type type_mnit__KeyEvent;
extern const int COLOR_physique__engine__KeyEvent__move;
extern const int COLOR_physique__engine__KeyEvent__move_bis;
extern const int COLOR_core__kernel__Object___61d_61d;
extern const int COLOR_physique__world__World__apply_event;
extern const int COLOR_mnit__input__KeyEvent__is_arrow_right;
extern const int COLOR_mnit__input__KeyEvent__is_arrow_left;
extern const int COLOR_mnit__input__KeyEvent__name;
