#include "nit.common.h"
val* BOX_core__Pointer(void*);
extern const struct type type_sdl__SDLDisplay;
extern const struct class class_sdl__SDLDisplay;
void* sdl___new_SDLDisplay___impl( long w, long h );
extern const int COLOR_sdl__SDLDisplay__enable_mouse_motion_events;
void sdl___SDLDisplay_destroy___impl( void* self );
void sdl___SDLDisplay_finish___impl( void* self );
void sdl___SDLDisplay_clear_int___impl( void* self, long r, long g, long b );
long sdl___SDLDisplay_width___impl( void* self );
long sdl___SDLDisplay_height___impl( void* self );
void sdl___SDLDisplay_fill_rect___impl( void* self, void* rect, long r, long g, long b );
void sdl___SDLDisplay_clear___impl( void* self, double r, double g, double b );
val* NEW_core__Array(const struct type* type);
extern const struct type type_core__Array__sdl__SDLInputEvent;
extern const int COLOR_core__kernel__Object__init;
extern const int COLOR_sdl__SDLDisplay__poll_event;
extern const int COLOR_core__kernel__Object___61d_61d;
extern const int COLOR_core__abstract_collection__SimpleCollection__add;
struct nitni_instance * sdl___SDLDisplay_poll_event___impl( void* self );
extern const int COLOR_sdl__SDLDisplay__new_key_event;
extern const int COLOR_sdl__SDLDisplay__new_mouse_motion_event;
extern const int COLOR_sdl__SDLDisplay__new_mouse_button_event;
extern const int COLOR_sdl__SDLDisplay__new_quit_event;
val* NEW_sdl__SDLKeyEvent(const struct type* type);
extern const struct type type_sdl__SDLKeyEvent;
val* core__flat___NativeString___core__abstract_text__Object__to_s(char* self);
extern const int COLOR_sdl__SDLKeyEvent__name_61d;
extern const int COLOR_sdl__SDLKeyEvent__down_61d;
val* NEW_sdl__SDLMouseMotionEvent(const struct type* type);
extern const struct type type_sdl__SDLMouseMotionEvent;
extern const int COLOR_sdl__SDLMouseMotionEvent__init;
val* NEW_sdl__SDLMouseButtonEvent(const struct type* type);
extern const struct type type_sdl__SDLMouseButtonEvent;
extern const int COLOR_sdl__SDLMouseButtonEvent__init;
val* NEW_sdl__SDLQuitEvent(const struct type* type);
extern const struct type type_sdl__SDLQuitEvent;
void sdl___SDLDisplay_warp_mouse___impl( void* self, long x, long y );
void sdl___SDLDisplay_show_cursor__assign___impl( void* self, int val );
int sdl___SDLDisplay_show_cursor___impl( void* self );
void sdl___SDLDisplay_grab_input__assign___impl( void* self, int val );
int sdl___SDLDisplay_grab_input___impl( void* self );
int sdl___SDLDisplay_ignore_mouse_motion_events___impl( void* self );
void sdl___SDLDisplay_ignore_mouse_motion_events__assign___impl( void* self, int val );
int sdl___SDLDisplay_mouse_focus___impl( void* self );
int sdl___SDLDisplay_input_focus___impl( void* self );
extern const int COLOR_mnit__display__Drawable__I;
extern const char FILE_sdl[];
extern const int COLOR_core__kernel__Numeric__to_i;
extern const int COLOR_sdl__SDLDrawable__native_blit;
void sdl___SDLDrawable_native_blit___impl( void* self, void* img, long x, long y );
extern const int COLOR_mnit__display__Sized__width;
extern const struct type type_core__Int;
extern const char FILE_core__kernel[];
extern const int COLOR_core__kernel__Numeric___45d;
extern const int COLOR_mnit__display__Sized__height;
extern const int COLOR_mnit__display__Drawable__blit;
extern const struct type type_sdl__SDLImage;
extern const struct class class_sdl__SDLImage;
void* sdl___new_SDLImage_from_file___impl( struct nitni_instance * path );
extern const int COLOR_core__abstract_text__Text__to_cstring;
void* sdl___new_SDLImage_copy_of___impl( void* image );
void sdl___SDLImage_save_to_file___impl( void* self, struct nitni_instance * path );
void sdl___SDLImage_destroy___impl( void* self );
long sdl___SDLImage_width___impl( void* self );
long sdl___SDLImage_height___impl( void* self );
extern const int COLOR_core__kernel__Pointer__address_is_null;
extern const struct type type_c__NativeCByteArray;
extern const struct class class_c__NativeCByteArray;
void* sdl___SDLImage_pixels___impl( void* self );
long sdl___SDLImage_amask___impl( void* self );
extern const struct type type_sdl__SDLRectangle;
extern const struct class class_sdl__SDLRectangle;
void* sdl___new_SDLRectangle___impl( long x, long y, long w, long h );
void sdl___SDLRectangle_x__assign___impl( void* self, long v );
long sdl___SDLRectangle_x___impl( void* self );
void sdl___SDLRectangle_y__assign___impl( void* self, long v );
long sdl___SDLRectangle_y___impl( void* self );
void sdl___SDLRectangle_w__assign___impl( void* self, long v );
long sdl___SDLRectangle_w___impl( void* self );
void sdl___SDLRectangle_h__assign___impl( void* self, long v );
long sdl___SDLRectangle_h___impl( void* self );
extern const int COLOR_sdl__SDLMouseEvent___x;
extern const int COLOR_sdl__SDLMouseEvent___y;
extern const int COLOR_sdl___sdl__SDLMouseEvent___core__kernel__Object__init;
extern const int COLOR_sdl__SDLMouseButtonEvent___button;
extern const int COLOR_sdl__SDLMouseButtonEvent___pressed;
extern const int COLOR_sdl__SDLMouseButtonEvent__button;
extern const int COLOR_sdl__SDLMouseButtonEvent__is_down_wheel;
extern const int COLOR_sdl__SDLMouseButtonEvent__is_up_wheel;
extern const int COLOR_sdl__SDLMouseEvent__x_61d;
extern const int COLOR_sdl__SDLMouseEvent__y_61d;
extern const int COLOR_sdl__SDLMouseButtonEvent__button_61d;
extern const int COLOR_sdl__SDLMouseButtonEvent__pressed_61d;
extern const int COLOR_mnit__input__PointerEvent__pressed;
val* NEW_core__NativeArray(int length, const struct type* type);
extern const struct type type_core__NativeArray__core__String;
val* core__flat___NativeString___to_s_full(char* self, long p0, long p1);
val* core__flat___Int___core__abstract_text__Object__to_s(long self);
extern const int COLOR_mnit__input__PointerEvent__x;
val* core__abstract_text___Float___Object__to_s(double self);
extern const int COLOR_mnit__input__PointerEvent__y;
extern const int COLOR_core__abstract_text__NativeArray__native_to_s;
extern const int COLOR_sdl__SDLMouseMotionEvent___rel_x;
extern const int COLOR_sdl__SDLMouseMotionEvent___rel_y;
extern const int COLOR_sdl__SDLMouseMotionEvent___pressed;
extern const int COLOR_sdl__SDLMouseMotionEvent__rel_x_61d;
extern const int COLOR_sdl__SDLMouseMotionEvent__rel_y_61d;
extern const int COLOR_sdl__SDLMouseMotionEvent__pressed_61d;
extern const int COLOR_sdl__SDLKeyEvent___name;
extern const int COLOR_sdl__SDLKeyEvent___down;
extern const int COLOR_mnit__input__KeyEvent__name;
extern const int COLOR_core__abstract_text__Text__length;
extern const int COLOR_core__abstract_text__Text__chars;
extern const int COLOR_core__abstract_collection__Collection__first;
extern const int COLOR_sdl__SDLKeyEvent__down;
extern const int COLOR_sdl___sdl__SDLKeyEvent___core__kernel__Object__init;
void sdl___Int_delay___impl( long self );
extern const struct type type_sdl__SDLFont;
extern const struct class class_sdl__SDLFont;
void* sdl___new_SDLFont___impl( struct nitni_instance * name, long points );
void sdl___SDLFont_destroy___impl( void* self );
void* sdl___SDLFont_render___impl( void* self, struct nitni_instance * text, long r, long g, long b );
long sdl___SDLFont_height___impl( void* self );
long sdl___SDLFont_ascent___impl( void* self );
long sdl___SDLFont_descent___impl( void* self );
long sdl___SDLFont_line_skip___impl( void* self );
int sdl___SDLFont_is_fixed_width___impl( void* self );
struct nitni_instance * sdl___SDLFont_family_name___impl( void* self );
struct nitni_instance * sdl___SDLFont_style_name___impl( void* self );
long sdl___SDLFont_width_of___impl( void* self, struct nitni_instance * text );
extern const struct type type_sdl__SDLSystemWindowManagerInfo;
extern const struct class class_sdl__SDLSystemWindowManagerInfo;
void* sdl___new_SDLSystemWindowManagerInfo___impl(  );
extern const struct type type_core__Pointer;
extern const struct class class_core__Pointer;
void* sdl___SDLSystemWindowManagerInfo_x11_window_handle___impl( void* self );
